export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TRACK_LOCKED: "TRACK_LOCKED",
  SCENE_NOT_FOUND: "SCENE_NOT_FOUND"
} as const;
