export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  SCENE_FORM_INVALID: "SCENE_FORM_INVALID",
  SCENE_NOT_FOUND: "SCENE_NOT_FOUND",
  TRACK_LOCKED: "TRACK_LOCKED",
  TRACK_NOT_FOUND: "TRACK_NOT_FOUND"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
